---
- name: "Check if Solr Service Exists"
  win_command: "sc query {{ solr_service_name }}"
  register: solr_service_stat
  ignore_errors: True

- name: "Set solr service status"
  set_fact:
    solr_service_status: "{{ solr_service_stat.rc == 0 }}"

- name: "Remove solr service"
  win_service:
    name: "{{ solr_service_name }}"
    state: absent

- name: "Remove Solr directory"
  win_file:
    path: "{{ dest_solr_path }}"
    state: absent
